---
- name: Set up alternatives
  hosts: all
  become: yes
  gather_facts: False
  
  tasks:
  - name: iptables
    community.general.alternatives:
      name: iptables
      #path: /usr/sbin/iptables-legacy
      path: /usr/sbin/iptables-nft 
  - name: Rebooting machine
    reboot:
      msg: "Rebooting after ansible updates"
      pre_reboot_delay: 1    
