---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server-lb
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    k8s-app: metrics-server
  type: LoadBalancer
