---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server-lb
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    k8s-app: metrics-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-lb
  namespace: kube-system
spec:
  loadBalancerIP: 10.0.0.230
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  type: LoadBalancer
