---
# See https://microk8s.io/docs
- name: Install microk8s
  hosts: all
  become: yes
  gather_facts: True
  
  tasks:
  
  - name: Install microk8s
    snap:
      name: microk8s
      classic: yes
#      channel: latest/stable
      channel: latest/edge
  
  - name: Setup users in groups
    shell:
      cmd: usermod -a -G microk8s {{ item }}
    with_items: 
      - george
    
  - name: Setup user ownership of .kube directory
    file:
      path: "/home/{{ item }}/.kube"
      owner: "{{ item }}"
      recurse: yes
    #shell:
    #  cmd: chown -f -R {{ item }} /home/{{ item }}/.kube
    with_items: 
      - george
    
  - name: Wait ready...
    shell:
      cmd: microk8s status --wait-ready
      
  - name: Enable dns on master
    when: inventory_hostname in groups[ 'master_node' ]
    shell:
      cmd: microk8s enable dns
  
  - name: add nodes to master
    tags:
      - add-nodes
    when: inventory_hostname not in groups[ 'master_node' ]
    block:
      - name: run add-node on master
        delegate_to: "{{ groups[ 'master_node' ][0] }}"
        shell:
          cmd: microk8s add-node
        register: command_output

      - name: Output all add-node output
        when: inventory_hostname not in groups[ 'master_node' ]
        debug:
          var: command_output.stdout_lines

      - name: cluster join line
        when: inventory_hostname not in groups[ 'master_node' ]
        debug:
          var: command_output.stdout_lines[1]
          
      - name: join cluster
        when: inventory_hostname not in groups[ 'master_node' ]
        shell:
          cmd: "{{ command_output.stdout_lines[1] }}"
        
    
