---
# See https://microk8s.io/docs
- name: Remove microk8s
  hosts: all
  become: yes
  gather_facts: False
  
  tasks:
  
  - name: Remove microk8s
    snap:
      name: microk8s
      state: absent
      
  - name: Removing microk8s snap snapshots
    shell: snap saved | grep microk8s | awk '{ print $1 }' | xargs -I % snap forget %
    ignore_errors: True
 
