---
- name: Remove kubeadm
  hosts: all
  become: yes
  gather_facts: False
  
  tasks:
  - name: Remove kubeadm
    apt:
      name: kubeadm
      state: absent
  - name: Remove kubelet
    apt:
      name: kubelet
      state: absent
  - name: Remove kubectl
    apt:
      name: kubectl
      state: absent
  - name: Autoclean
    apt:
      autoclean: yes
  - name: Autoremove
    apt:
      autoremove: yes

