---
apiVersion: v1
kind: Service
metadata:
  name: kube-longhorn-ui
  namespace: ${longhorn-namespace}
  labels:
    service-type: external
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: longhorn-ui
  type: LoadBalancer
