---
#See https://metallb.org/
- name: Install MetalLB into the cluster
  hosts: master_node
  become: no
  gather_facts: False
  vars:
    metallb_namespace: metallb

  tasks:
    - name: add metallb repo
      kubernetes.core.helm_repository:
        name: metallb
        url: https://metallb.github.io/metallb
        state: present

    - name: helm install metallb
      kubernetes.core.helm:
        binary_path: microk8s helm3
        name: metallb
        update_repo_cache: yes
        chart_ref: metallb/metallb
        release_namespace: "{{ metallb_namespace }}"
        create_namespace: yes
        values:
          configInline:
            address-pools:
            - name: default
              protocol: layer2
              addresses:
              - 10.0.0.200-10.0.0.229
            - name: fixed-services
              protocol: layer2
              addresses:
              - 10.0.0.230-10.0.0.240
              auto-assign: false

