---
- hosts: all
  gather_facts: False
  become: yes
  
  tasks:
  - name: Start microk8s on master
    when: inventory_hostname in groups[ 'master_node' ]
    ansible.builtin.shell:
      cmd: microk8s start

  - name: Wait for master to be ready
    when: inventory_hostname in groups[ 'master_node' ]
    ansible.builtin.shell:
      cmd: microk8s status --wait-ready

  - name: Start microk8s on non-master
    when: inventory_hostname not in groups[ 'master_node' ]
    ansible.builtin.shell:
      cmd: microk8s start

  - name: Wait for master to be ready
    when: inventory_hostname not in groups[ 'master_node' ]
    ansible.builtin.shell:
      cmd: microk8s status --wait-ready
