# This playbook will build a new kernel using the existing configuration + the following:
# - vxlan as a module
# - sysfs_btf in kernel
#
# vxlan requires the udp_tunnel and ip6_udp_tunnel modules to be available.
#
# Prior to Running this ensure that deb-srcs are available on localhost
#   Uncomment deb-src entries: - see instructions at https://forums.raspberrypi.com/viewtopic.php?f=131&t=284556&p=1734458#p1734458
#   For example, Add following lines to /etc/apt/sources.list for jammy release
#   | deb-src http://ports.ubuntu.com/ubuntu-ports jammy main restricted
#   | deb-src http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted
#
---
- name: Build kernel with vxlan and sysfs_btf
  hosts: all
  become: False
  gather_facts: True

  tasks:

  - name: versions
    block:
    - name: Get kernel version
      ansible.builtin.shell:
        cmd: uname -r
      register: kernel_version
    - name: Output kernel version
      ansible.builtin.debug:
        msg: "Kernel Version: {{ kernel_version.stdout }}"
    - name: Generate base version
      ansible.builtin.shell:
        cmd: "echo \"{{ kernel_version.stdout }}\" | awk -F '\\\\.|-' '{ print $1\".\"$2\".\"$3 }'"
      register: base_version
    - name: Output base version
      ansible.builtin.debug:
        msg: "Base Version: {{ base_version.stdout }}"

  - name: all node preparation 1
    delegate_to: localhost
    become: False
    block:
    - name: Get local root directory
      ansible.builtin.shell:
        cmd: echo /home/$USER/linux
      register: build_root
    - name: Output local root directory
      ansible.builtin.debug:
        msg: "Build root: {{ build_root.stdout }}"
    - name: Get search version
      ansible.builtin.shell:
        cmd: "echo \"{{ kernel_version.stdout }}\" | awk -F '\\\\.|-' '{ print $1\".\"$2\".\"$3\"-\"$4 }'"
      register: search_version
    - name: Output search version
      ansible.builtin.debug:
        msg: "Search Version: {{ search_version.stdout }}"
    - name: Generate linux source directory
      ansible.builtin.shell:
        cmd: echo "{{ build_root.stdout }}/linux-raspi-{{ base_version.stdout }}"
      register: source_dir
    - name: Output linux source directory
      ansible.builtin.debug:
        msg: "Source Directory: {{ source_dir.stdout }}"

  - name: local preparation
    when: inventory_hostname in groups[ 'master_node' ]
    delegate_to: localhost
    block:
    - name: Ensure local root directory
      ansible.builtin.file:
        path: "{{ build_root.stdout }}"
        state: directory
    - name: Clean up any previous source 
      ansible.builtin.file:
        path: "{{ source_dir.stdout }}"
        state: absent
    - name: Ensure build dependencies
      become: True
      ansible.builtin.apt:
        update_cache: True
        state: present
        pkg:
        - gcc-aarch64-linux-gnu
        - flex
        - bison
        - libssl-dev
        - libelf-dev
        - fakeroot
        - pahole
        - libncurses-dev

  - name: get source on localhost
    when: inventory_hostname in groups[ 'master_node' ]
    delegate_to: localhost
    block:
    - name: Get source
      ansible.builtin.shell:
        chdir: "{{ build_root.stdout }}"
        cmd: apt source linux-image-{{ kernel_version.stdout }}

  - name: all node preparation 2
    delegate_to: localhost
    become: False
    block:
    - name: Get specific version
      ansible.builtin.shell:
        chdir: "{{ source_dir.stdout }}"
        cmd: cat debian.raspi/changelog | grep -oP '\({{ search_version.stdout }}.*\)' | sed 's/(//g' | sed 's/)//g'
      register: specific_version
    - name: Output specific version
      ansible.builtin.debug:
        msg: "Specific Version: {{ specific_version.stdout }}"
    - name: Generate new version
      ansible.builtin.shell:
        cmd: "echo \"{{ specific_version.stdout }}+btf\""
      register: new_version
    - name: Output new version
      ansible.builtin.debug:
        msg: "New Version: {{ new_version.stdout }}"

  - name: get ready to build on localhost
    when: inventory_hostname in groups[ 'master_node' ]
    delegate_to: localhost
    block:
    - name: update config settings
      ansible.builtin.shell:
        chdir: "{{ source_dir.stdout }}"
        cmd: "scripts/config --file debian.raspi/config/config.common.ubuntu {{ item.change }} {{ item.config }}"
      loop:
      - { change: '--enable', config: 'DEBUG_INFO_BTF' } 
      - { change: '--module', config: 'VXLAN' } 
      - { change: '--disable', config: 'DEBUG_INFO_DWARF4' } 
      - { change: '--disable', config: 'DEBUG_INFO_DWARF5' } 
      - { change: '--enable', config: 'DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT' }
    - name: Patch up changelog (add suffix)
      block:
      - name: replace version with new version in debian.raspi/changelog
        ansible.builtin.replace:
          path: "{{ source_dir.stdout }}/debian.raspi/changelog"
          regexp: 'linux-raspi \({{ specific_version.stdout }}\) '
          replace: 'linux-raspi ({{ new_version.stdout }}) '
    - name: run build commands
      ansible.builtin.debug:
        msg: |-
          # Now Run the following in {{ source_dir.stdout }}
          export ARCH=arm64
          export $(dpkg-architecture -aarm64)
          export CROSS_COMPILE=aarch64-linux-gnu-
          fakeroot debian/rules clean
          debian/rules build
          fakeroot debian/rules binary

  - name: copy files to remotes
    block:
    - name: make remote directory
      ansible.builtin.file:
        path: /tmp/kernels
        state: directory
    - name: copy image
      ansible.builtin.copy:
        src: "{{ build_root.stdout }}/{{ item.local }}"
        dest: "/tmp/kernels/{{ item.remote }}"
        force: True
      loop:
      - { local: 'linux-image-{{ kernel_version.stdout }}_{{ new_version.stdout }}_arm64.deb', remote: 'linux-image_arm64.deb' }
      - { local: 'linux-modules-{{ kernel_version.stdout }}_{{ new_version.stdout }}_arm64.deb', remote: 'linux-modules_arm64.deb' }
      - { local: 'linux-modules-extra-{{ kernel_version.stdout }}_{{ new_version.stdout }}_arm64.deb', remote: 'linux-modules-extra_arm64.deb' }
